export const ActionsType = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    SET_PRODUCTS_BY_CATEGORY: "SET_PRODUCTS_BY_CATEGORY",
    RATING_FILTER: "RATING_FILTER",
    PRICE_FILTER: "PRICE_FILTER",
    SEARCH_PRODUCTS: "SEARCH_PRODUCTS", 
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST"
}